### PR TITLE
Add Symfony 6 support

### LINKED ISSUE #86: Adds support for Symfony 6.x

### PR DESCRIPTION
**Pull request by Korbeil**
Fixes #86

### CODE REVIEW

**Comment by jcchavezs** [comment]
Thanks for this @Korbeil do you mind running the linter?

**Comment by Korbeil** [comment]
It should be better @jcchavezs ? Sorry for the delay

**Comment by jcchavezs** [comment]
Let me check.

**Comment by Korbeil** [comment]
@jcchavezs Could you run tests again pls ?

**Comment by jcchavezs** [comment]
Thanks @Korbeil 

A couple of things:
1. I would create a function

```
function isMainRequest() {
return (Kernel::MAJOR_VERSION >= 6 && !$event->isMainRequest())
            || (Kernel::MAJOR_VERSION < 6 && !$event->isMasterRequest())
}
```
and also a `getMainRequest()` returning the request accordingly to be reused everywhere (function in a php file is fine).

On the other hand, I am not sure e2e are working (see https://github.com/jcchavezs/zipkin-instrumentation-symfony/blob/master/tests/E2E/build.sh#L37). web-server-bundle isn't working beyond symfony 5.0 so for 6.0 [this](https://symfony.com/doc/current/setup/symfony_server.html) should be used.

**Comment by Korbeil** [comment]
Even if we switch to Symfony CLI, the current CI is not usable anymore since you can't force a Symfony version into Symfony CLI. I'll try to look for another way of doing that kind of tests.

**Comment by Korbeil** [comment]
And it's all fixed ! I removed the CircleCI part and migrated everything into Github Actions.
It's still not perfect but it should run as you want for now ~

You can see the full workflow here: https://github.com/Korbeil/zipkin-instrumentation-symfony/pull/1 (I enabled Actions on my fork to test it)

**Comment by Korbeil** [comment]
I made a few more changes, could you run the CI again ? Do you have any feedback on the changes ?

**Comment by jcchavezs** [comment]
Let me review in dept. So far I would say we should use the build.sh script to build the example apps instead of inline in yaml https://github.com/jcchavezs/zipkin-instrumentation-symfony/pull/89/files#diff-bb4cd38e17bbeb0e8e2a41292fec692241a9b14029ad655938d61994ed9197a4R135

**Comment by Korbeil** [comment]
> Let me review in dept. So far I would say we should use the build.sh script to build the example apps instead of inline in yaml https://github.com/jcchavezs/zipkin-instrumentation-symfony/pull/89/files#diff-bb4cd38e17bbeb0e8e2a41292fec692241a9b14029ad655938d61994ed9197a4R135

Everything now uses the `tests/E2E` scripts, you can run CI again.

**Pull request closed without merging**
